server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://10.210.1.135:13066/OW
    username: USR_TST
    password: Owtest1#2!

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.example